name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Run ESLint
      run: npm run lint

    - name: Build package
      if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
      run: |
        npm run build
        npm pack

    - name: Upload artifact
      if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: "*.tgz"