name: CI Pipeline to PR

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Run ESLint
      run: npm run lint

    - name: Build package
      run: |
        npm run build
        npm pack

on:
  push:
    branches:
      - '**'  # Este flujo se ejecuta en cualquier push a cualquier rama

jobs:
  ci:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'CI=true')  # Verifica si el mensaje contiene 'CI=true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Run ESLint
      run: npm run lint

    - name: Build package
      run: |
        npm run build
        npm pack