name: On Merge to Develop deploy jfrog develop

on:
  push:
    branches:
      - develop  # Esta es la rama develop, cambia si tu rama se llama de otra manera

jobs:
  deploy-jfrog-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: |
          npm run build
          npm pack

      # Paso para enviar el mensaje a un servidor
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: "*.tgz"