name: On Merge to Develop Workflow

on:
  push:
    branches:
      - develop  # Esta es la rama develop, cambia si tu rama se llama de otra manera

jobs:
  deploy-jfrog:
    runs-on: ubuntu-latest

    steps:
      # Paso para hacer checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso para enviar el mensaje a un servidor
      - name: Send message to server (example)
        run: |
          curl -X POST https://httpbin.org/post \
          -H "Content-Type: application/json" \
          -d '{"message": "Merge realizado exitosamente en la rama develop"}'