name: On Merge to Develop deploy jfrog develop

on:
  push:
    branches:
      - develop  # Esta es la rama develop, cambia si tu rama se llama de otra manera

jobs:
  deploy-jfrog-develop:
    runs-on: ubuntu-latest

    steps:
      # Paso para hacer checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build package
        run: |
          npm run build
          npm pack

      # Paso para enviar el mensaje a un servidor
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: "*.tgz"