name: On Merge Workflow deploy jfrog main

on:
  push:
    branches:
      - main # Cambia 'main' por la rama destino de tu merge si es diferente

jobs:
  deploy-jfrog-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send message to server (example)
        run: |
          curl -X POST https://httpbin.org/post \
          -H "Content-Type: application/json" \
          -d '{"message": "Merge realizado exitosamente en la rama main"}'